/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Personalinformation.Demographicinfo;
import Personalinformation.Addressinfo;

import javax.swing.JOptionPane;

/**
 *
 * @author murgod
 */
public class createDemographicInfoJpanel extends javax.swing.JPanel {

    /**
     * Creates new form createDemographicInfoJpanel
     */
    private Demographicinfo demographicinfo;
    private Addressinfo addressinfo;
    
    public createDemographicInfoJpanel(Demographicinfo demographicinfo) {
        initComponents();
        this.demographicinfo=demographicinfo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstnamelabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        phnolabel = new javax.swing.JLabel();
        doblabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        heightlable = new javax.swing.JLabel();
        weightlabel = new javax.swing.JLabel();
        ssnlabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        secondNameTextField = new javax.swing.JTextField();
        phonenotextfield = new javax.swing.JTextField();
        dobtextfield = new javax.swing.JTextField();
        agetextfield = new javax.swing.JTextField();
        heighttextfield = new javax.swing.JTextField();
        weighttextfield = new javax.swing.JTextField();
        ssntextfield = new javax.swing.JTextField();
        saveDemographicalInfoButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter Demographic Info");

        firstnamelabel.setText("firstname");

        lastnamelabel.setText("lastname");

        phnolabel.setText("phoneno");

        doblabel.setText("DOB");

        agelabel.setText("age");

        heightlable.setText("height");

        weightlabel.setText("weight");

        ssnlabel.setText("ssn");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        secondNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondNameTextFieldActionPerformed(evt);
            }
        });

        saveDemographicalInfoButton.setText("save");
        saveDemographicalInfoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveDemographicalInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveDemographicalInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDemographicalInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnamelabel)
                            .addComponent(lastnamelabel)
                            .addComponent(phnolabel)
                            .addComponent(doblabel)
                            .addComponent(agelabel)
                            .addComponent(heightlable)
                            .addComponent(weightlabel)
                            .addComponent(ssnlabel))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssntextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(weighttextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addComponent(heighttextfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(agetextfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dobtextfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(phonenotextfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(secondNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(saveDemographicalInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamelabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamelabel)
                    .addComponent(secondNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phnolabel)
                    .addComponent(phonenotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doblabel)
                    .addComponent(dobtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelabel)
                    .addComponent(agetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightlable)
                    .addComponent(heighttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightlabel)
                    .addComponent(weighttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnlabel)
                    .addComponent(ssntextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(saveDemographicalInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void secondNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondNameTextFieldActionPerformed

    private void saveDemographicalInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDemographicalInfoButtonActionPerformed
        // TODO add your handling code here:
        demographicinfo.setFirstname(firstNameTextField.getText());
        demographicinfo.setLastname(secondNameTextField.getText());
        demographicinfo.setPhonenumber(phonenotextfield.getText());
        demographicinfo.setDob(dobtextfield.getText());
        demographicinfo.setAge(agetextfield.getText());
        demographicinfo.setHeight(heighttextfield.getText());
        demographicinfo.setSsn(ssntextfield.getText());
        
        JOptionPane.showMessageDialog(null, "Demographic Information saved successfully");
    }//GEN-LAST:event_saveDemographicalInfoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agelabel;
    private javax.swing.JTextField agetextfield;
    private javax.swing.JLabel doblabel;
    private javax.swing.JTextField dobtextfield;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JLabel heightlable;
    private javax.swing.JTextField heighttextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JLabel phnolabel;
    private javax.swing.JTextField phonenotextfield;
    private javax.swing.JButton saveDemographicalInfoButton;
    private javax.swing.JTextField secondNameTextField;
    private javax.swing.JLabel ssnlabel;
    private javax.swing.JTextField ssntextfield;
    private javax.swing.JLabel weightlabel;
    private javax.swing.JTextField weighttextfield;
    // End of variables declaration//GEN-END:variables
}
