/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Personalinformation.Checkingaccountinfo;

/**
 *
 * @author murgod
 */
public class createcheckingJpanel extends javax.swing.JPanel {

    /**
     * Creates new form createcheckingJpanel
     */
    private Checkingaccountinfo checkingaccountinfo;
    public createcheckingJpanel(Checkingaccountinfo checkingaccountinfo) {
        initComponents();
        this.checkingaccountinfo=checkingaccountinfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstnamelabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        phnolabel = new javax.swing.JLabel();
        doblabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        CheckAccBankName = new javax.swing.JTextField();
        ChkAccBankRoutingNo = new javax.swing.JTextField();
        ChkAccBankAccNo = new javax.swing.JTextField();
        ChkAccBalance = new javax.swing.JTextField();
        chkAccType = new javax.swing.JTextField();
        SaveCheckingAccInfo = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Checking Account Info");

        firstnamelabel.setText("Bank name");

        lastnamelabel.setText("Bank Routing no");

        phnolabel.setText("Bank Acc no");

        doblabel.setText("Account Balance");

        agelabel.setText("Account type");

        CheckAccBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAccBankNameActionPerformed(evt);
            }
        });

        ChkAccBankRoutingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkAccBankRoutingNoActionPerformed(evt);
            }
        });

        ChkAccBankAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkAccBankAccNoActionPerformed(evt);
            }
        });

        SaveCheckingAccInfo.setText("Save");
        SaveCheckingAccInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCheckingAccInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnamelabel)
                            .addComponent(lastnamelabel)
                            .addComponent(phnolabel)
                            .addComponent(doblabel)
                            .addComponent(agelabel))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkAccType, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(ChkAccBalance)
                            .addComponent(ChkAccBankAccNo)
                            .addComponent(ChkAccBankRoutingNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CheckAccBankName)
                            .addComponent(SaveCheckingAccInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamelabel)
                    .addComponent(CheckAccBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamelabel)
                    .addComponent(ChkAccBankRoutingNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phnolabel)
                    .addComponent(ChkAccBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doblabel)
                    .addComponent(ChkAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelabel)
                    .addComponent(chkAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(SaveCheckingAccInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CheckAccBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAccBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckAccBankNameActionPerformed

    private void ChkAccBankRoutingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkAccBankRoutingNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkAccBankRoutingNoActionPerformed

    private void ChkAccBankAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkAccBankAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkAccBankAccNoActionPerformed

    private void SaveCheckingAccInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCheckingAccInfoActionPerformed
        // TODO add your handling code here:
        checkingaccountinfo.setBankname(CheckAccBankName.getText());
        checkingaccountinfo.setBankroutingno(ChkAccBankRoutingNo.getText());
        checkingaccountinfo.setBankAccNo(ChkAccBankAccNo.getText());
        checkingaccountinfo.setBankaccountbalance(ChkAccBalance.getText());
        checkingaccountinfo.setAccounttype(chkAccType.getText());
    }//GEN-LAST:event_SaveCheckingAccInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CheckAccBankName;
    private javax.swing.JTextField ChkAccBalance;
    private javax.swing.JTextField ChkAccBankAccNo;
    private javax.swing.JTextField ChkAccBankRoutingNo;
    private javax.swing.JButton SaveCheckingAccInfo;
    private javax.swing.JLabel agelabel;
    private javax.swing.JTextField chkAccType;
    private javax.swing.JLabel doblabel;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JLabel phnolabel;
    // End of variables declaration//GEN-END:variables
}
