/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Personalinformation.Savingaccountinfo;
/**
 *
 * @author murgod
 */

public class createsavingJpanel extends javax.swing.JPanel {

    /**
     * Creates new form createsavingJpanel
     */
    private Savingaccountinfo savingaccountinfo;
    public createsavingJpanel(Savingaccountinfo savingaccountinfo) {
        initComponents();
        this.savingaccountinfo=savingaccountinfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstnamelabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        phnolabel = new javax.swing.JLabel();
        doblabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        BankNameTextFieldCreate = new javax.swing.JTextField();
        BankRoutingNoTextFieldCreate = new javax.swing.JTextField();
        BankAccNoTextFieldCreate = new javax.swing.JTextField();
        AccBalanceTextFieldCreate = new javax.swing.JTextField();
        AccTypeTextFieldCreate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("                  Enter Savings account Info");

        firstnamelabel.setText("Bank name");

        lastnamelabel.setText("Bank routing no");

        phnolabel.setText("Bank account no");

        doblabel.setText("Account balance");

        agelabel.setText("Account type");

        BankNameTextFieldCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankNameTextFieldCreateActionPerformed(evt);
            }
        });

        BankRoutingNoTextFieldCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankRoutingNoTextFieldCreateActionPerformed(evt);
            }
        });

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnamelabel)
                            .addComponent(lastnamelabel)
                            .addComponent(phnolabel)
                            .addComponent(doblabel)
                            .addComponent(agelabel))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AccTypeTextFieldCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(AccBalanceTextFieldCreate)
                            .addComponent(BankAccNoTextFieldCreate)
                            .addComponent(BankRoutingNoTextFieldCreate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BankNameTextFieldCreate)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamelabel)
                    .addComponent(BankNameTextFieldCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamelabel)
                    .addComponent(BankRoutingNoTextFieldCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phnolabel)
                    .addComponent(BankAccNoTextFieldCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doblabel)
                    .addComponent(AccBalanceTextFieldCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelabel)
                    .addComponent(AccTypeTextFieldCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BankNameTextFieldCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankNameTextFieldCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankNameTextFieldCreateActionPerformed

    private void BankRoutingNoTextFieldCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankRoutingNoTextFieldCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankRoutingNoTextFieldCreateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        savingaccountinfo.setBankname(BankNameTextFieldCreate.getText());
        savingaccountinfo.setBankroutingno(BankRoutingNoTextFieldCreate.getText());
        savingaccountinfo.setBankaccountno(BankAccNoTextFieldCreate.getText());
        savingaccountinfo.setAccountBalance(AccBalanceTextFieldCreate.getText());
        savingaccountinfo.setAccountType(AccTypeTextFieldCreate.getText());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccBalanceTextFieldCreate;
    private javax.swing.JTextField AccTypeTextFieldCreate;
    private javax.swing.JTextField BankAccNoTextFieldCreate;
    private javax.swing.JTextField BankNameTextFieldCreate;
    private javax.swing.JTextField BankRoutingNoTextFieldCreate;
    private javax.swing.JLabel agelabel;
    private javax.swing.JLabel doblabel;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JLabel phnolabel;
    // End of variables declaration//GEN-END:variables
}
