/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Personalinformation.Demographicinfo;
import Personalinformation.Addressinfo; 
import Personalinformation.Savingaccountinfo;
import Personalinformation.Checkingaccountinfo;
import Personalinformation.Driverlicenceinfo;
import Personalinformation.MedicalRecord;
/**
 *
 * @author murgod
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private Personalinformation personalinformation;
    private Demographicinfo demographicinfo;
    private Addressinfo addressinfo;
    private Savingaccountinfo savingaccountinfo;
    private Checkingaccountinfo checkingaccountinfo;
    private Driverlicenceinfo driverlicenceinfo;
    private MedicalRecord medicalRecord;
    private Object splitPanel;
    
    public MainJFrame() {
        initComponents();
        demographicinfo = new Demographicinfo();
        addressinfo = new Addressinfo();
        savingaccountinfo = new Savingaccountinfo();
        checkingaccountinfo =new Checkingaccountinfo();
        driverlicenceinfo = new Driverlicenceinfo();
        medicalRecord = new MedicalRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlJpanel = new javax.swing.JPanel();
        democreatebtn = new javax.swing.JButton();
        viewDemographicInfo = new javax.swing.JButton();
        createadrbtn = new javax.swing.JButton();
        viewadrbtn = new javax.swing.JButton();
        createsavingsbtn = new javax.swing.JButton();
        viewsavingsbtn = new javax.swing.JButton();
        createcheckingbtn = new javax.swing.JButton();
        viewcheckingbtn = new javax.swing.JButton();
        createdriverbtn = new javax.swing.JButton();
        viewdriverbtn = new javax.swing.JButton();
        createmedicalbtn = new javax.swing.JButton();
        viewmedicalbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        DisplayJpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(650, 750));

        democreatebtn.setText("Demographic Info");
        democreatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                democreatebtnActionPerformed(evt);
            }
        });

        viewDemographicInfo.setText("View Demographic Info");
        viewDemographicInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDemographicInfoActionPerformed(evt);
            }
        });

        createadrbtn.setText("Address Info");
        createadrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createadrbtnActionPerformed(evt);
            }
        });

        viewadrbtn.setText("View Address Info");
        viewadrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewadrbtnActionPerformed(evt);
            }
        });

        createsavingsbtn.setText(" SavingAccount Info");
        createsavingsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createsavingsbtnActionPerformed(evt);
            }
        });

        viewsavingsbtn.setText("View SavingsAccount Info");
        viewsavingsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsavingsbtnActionPerformed(evt);
            }
        });

        createcheckingbtn.setText("CheckingAccount Info");
        createcheckingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createcheckingbtnActionPerformed(evt);
            }
        });

        viewcheckingbtn.setText("View Checking Info");
        viewcheckingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcheckingbtnActionPerformed(evt);
            }
        });

        createdriverbtn.setText("Driverlicence Info");
        createdriverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdriverbtnActionPerformed(evt);
            }
        });

        viewdriverbtn.setText("View Driverlicence Info");
        viewdriverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdriverbtnActionPerformed(evt);
            }
        });

        createmedicalbtn.setText("Medical Record");
        createmedicalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createmedicalbtnActionPerformed(evt);
            }
        });

        viewmedicalbtn.setText("View MedicalRecord");
        viewmedicalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmedicalbtnActionPerformed(evt);
            }
        });

        jButton1.setText("View Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlJpanelLayout = new javax.swing.GroupLayout(ControlJpanel);
        ControlJpanel.setLayout(ControlJpanelLayout);
        ControlJpanelLayout.setHorizontalGroup(
            ControlJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewdriverbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createmedicalbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewmedicalbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createdriverbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewcheckingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createcheckingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewsavingsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createsavingsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewadrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createadrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewDemographicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(democreatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        ControlJpanelLayout.setVerticalGroup(
            ControlJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(democreatebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDemographicInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createadrbtn)
                .addGap(8, 8, 8)
                .addComponent(viewadrbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createsavingsbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewsavingsbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createcheckingbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewcheckingbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createdriverbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewdriverbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createmedicalbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewmedicalbtn)
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(ControlJpanel);

        javax.swing.GroupLayout DisplayJpanelLayout = new javax.swing.GroupLayout(DisplayJpanel);
        DisplayJpanel.setLayout(DisplayJpanelLayout);
        DisplayJpanelLayout.setHorizontalGroup(
            DisplayJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        DisplayJpanelLayout.setVerticalGroup(
            DisplayJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(DisplayJpanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void democreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_democreatebtnActionPerformed
        createDemographicInfoJpanel createJpane1; 
        createJpane1 = new createDemographicInfoJpanel(demographicinfo); 
        jSplitPane1.setRightComponent(createJpane1);
    }//GEN-LAST:event_democreatebtnActionPerformed

    private void viewDemographicInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDemographicInfoActionPerformed
        // TODO add your handling code here:
        viewDemographicInfoJpanel viewdemo = new viewDemographicInfoJpanel(demographicinfo);
        jSplitPane1.setRightComponent(viewdemo);
        
    }//GEN-LAST:event_viewDemographicInfoActionPerformed

    private void viewadrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewadrbtnActionPerformed
        viewAddrJpanel viewdemo1;
        viewdemo1 = new viewAddrJpanel(addressinfo);
        jSplitPane1.setRightComponent(viewdemo1);
    }//GEN-LAST:event_viewadrbtnActionPerformed

    private void createsavingsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createsavingsbtnActionPerformed
        // TODO add your handling code here:
        createsavingJpanel createJpane12; 
        createJpane12 = new createsavingJpanel(savingaccountinfo); 
        jSplitPane1.setRightComponent(createJpane12);
    }//GEN-LAST:event_createsavingsbtnActionPerformed

    private void viewcheckingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcheckingbtnActionPerformed
        // TODO add your handling code here:
        viewcheckingJpanel viewdemo3 = new viewcheckingJpanel(checkingaccountinfo);
        jSplitPane1.setRightComponent(viewdemo3);
    }//GEN-LAST:event_viewcheckingbtnActionPerformed

    private void createadrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createadrbtnActionPerformed
       createAddrJpanel createJpane11; 
       createJpane11 = new createAddrJpanel(addressinfo); 
       jSplitPane1.setRightComponent(createJpane11); 
    }//GEN-LAST:event_createadrbtnActionPerformed

    private void createdriverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdriverbtnActionPerformed
        // TODO add your handling code here:
        createdriverJpanel createJpane14; 
        createJpane14 = new createdriverJpanel(driverlicenceinfo); 
        jSplitPane1.setRightComponent(createJpane14);
    }//GEN-LAST:event_createdriverbtnActionPerformed

    private void createcheckingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createcheckingbtnActionPerformed
        // TODO add your handling code here:
        createcheckingJpanel createJpane13; 
        createJpane13 = new createcheckingJpanel(checkingaccountinfo); 
        jSplitPane1.setRightComponent(createJpane13);
    }//GEN-LAST:event_createcheckingbtnActionPerformed

    private void viewdriverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdriverbtnActionPerformed
        // TODO add your handling code here:
        viewdriverJpanel viewdemo4 = new viewdriverJpanel(driverlicenceinfo);
        jSplitPane1.setRightComponent(viewdemo4);
    }//GEN-LAST:event_viewdriverbtnActionPerformed

    private void createmedicalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createmedicalbtnActionPerformed
        // TODO add your handling code here:
        createmedicalJpanel createJpane15; 
        createJpane15 = new createmedicalJpanel(medicalRecord); 
        jSplitPane1.setRightComponent(createJpane15);
    }//GEN-LAST:event_createmedicalbtnActionPerformed

    private void viewmedicalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmedicalbtnActionPerformed
        // TODO add your handling code here:
        viewmedicalJpanel viewdemo5 = new viewmedicalJpanel(medicalRecord);
        jSplitPane1.setRightComponent(viewdemo5);
    }//GEN-LAST:event_viewmedicalbtnActionPerformed

    private void viewsavingsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsavingsbtnActionPerformed
        // TODO add your handling code here:
        viewsavingJpanel svingsJpanel = new viewsavingJpanel(savingaccountinfo);
        jSplitPane1.setRightComponent(svingsJpanel);
    }//GEN-LAST:event_viewsavingsbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         ViewDetailsScrolPanel view = new ViewDetailsScrolPanel(demographicinfo, addressinfo, savingaccountinfo, 
                            checkingaccountinfo,driverlicenceinfo, medicalRecord);
         jSplitPane1.setRightComponent(view);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlJpanel;
    private javax.swing.JPanel DisplayJpanel;
    private javax.swing.JButton createadrbtn;
    private javax.swing.JButton createcheckingbtn;
    private javax.swing.JButton createdriverbtn;
    private javax.swing.JButton createmedicalbtn;
    private javax.swing.JButton createsavingsbtn;
    private javax.swing.JButton democreatebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton viewDemographicInfo;
    private javax.swing.JButton viewadrbtn;
    private javax.swing.JButton viewcheckingbtn;
    private javax.swing.JButton viewdriverbtn;
    private javax.swing.JButton viewmedicalbtn;
    private javax.swing.JButton viewsavingsbtn;
    // End of variables declaration//GEN-END:variables
}
