/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Personalinformation.Savingaccountinfo;

/**
 *
 * @author akshay
 */
public class viewsavingJpanel extends javax.swing.JPanel {

    /**
     * Creates new form viewsavingJpanel
     */
    public viewsavingJpanel() {
        initComponents();
    }
    Savingaccountinfo savingaccountinfo;
    viewsavingJpanel(Savingaccountinfo savingaccountinfo) {
        initComponents();
        displaySavingsAccInfo(savingaccountinfo);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private void displaySavingsAccInfo(Savingaccountinfo savingaccountinfo){
        String BankName = savingaccountinfo.getBankname();
        BankNameTextFieldView.setText(BankName);
        
        String BankRoutingNo = savingaccountinfo.getBankroutingno();
        BankRoutingNoTextFieldView.setText(BankRoutingNo);
        
        String BankAccNo = savingaccountinfo.getBankaccountno();
        BankAccNoTextFieldView.setText(BankAccNo);
        
        String AccBalance = savingaccountinfo.getAccountBalance();
        AccBalanceTextFieldView.setText(AccBalance);
        
        String AccType = savingaccountinfo.getAccountType();
        AccTypeTextFieldView.setText(AccType);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        firstnamelabel = new javax.swing.JLabel();
        BankNameTextFieldView = new javax.swing.JTextField();
        BankRoutingNoTextFieldView = new javax.swing.JTextField();
        lastnamelabel = new javax.swing.JLabel();
        phnolabel = new javax.swing.JLabel();
        BankAccNoTextFieldView = new javax.swing.JTextField();
        AccBalanceTextFieldView = new javax.swing.JTextField();
        doblabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        AccTypeTextFieldView = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("View Savingaccount Info");

        firstnamelabel.setText("Bank name");

        BankNameTextFieldView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankNameTextFieldViewActionPerformed(evt);
            }
        });

        BankRoutingNoTextFieldView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankRoutingNoTextFieldViewActionPerformed(evt);
            }
        });

        lastnamelabel.setText("Bank routing no");

        phnolabel.setText("Bank account no");

        AccBalanceTextFieldView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccBalanceTextFieldViewActionPerformed(evt);
            }
        });

        doblabel.setText("Account balance");

        agelabel.setText("Account type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnamelabel)
                            .addComponent(lastnamelabel)
                            .addComponent(phnolabel)
                            .addComponent(doblabel)
                            .addComponent(agelabel))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AccTypeTextFieldView, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(AccBalanceTextFieldView)
                            .addComponent(BankAccNoTextFieldView)
                            .addComponent(BankRoutingNoTextFieldView, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BankNameTextFieldView))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamelabel)
                    .addComponent(BankNameTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamelabel)
                    .addComponent(BankRoutingNoTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phnolabel)
                    .addComponent(BankAccNoTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doblabel)
                    .addComponent(AccBalanceTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelabel)
                    .addComponent(AccTypeTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BankNameTextFieldViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankNameTextFieldViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankNameTextFieldViewActionPerformed

    private void BankRoutingNoTextFieldViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankRoutingNoTextFieldViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankRoutingNoTextFieldViewActionPerformed

    private void AccBalanceTextFieldViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccBalanceTextFieldViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccBalanceTextFieldViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccBalanceTextFieldView;
    private javax.swing.JTextField AccTypeTextFieldView;
    private javax.swing.JTextField BankAccNoTextFieldView;
    private javax.swing.JTextField BankNameTextFieldView;
    private javax.swing.JTextField BankRoutingNoTextFieldView;
    private javax.swing.JLabel agelabel;
    private javax.swing.JLabel doblabel;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JLabel phnolabel;
    // End of variables declaration//GEN-END:variables
}
